export const PROVINCE_LIST = [
  { pid: '81', v: 'กระบี่' },
  { pid: '10', v: 'กรุงเทพมหานคร' },
  { pid: '71', v: 'กาญจนบุรี' },
  { pid: '46', v: 'กาฬสินธุ์' },
  { pid: '62', v: 'กำแพงเพชร' },
  { pid: '40', v: 'ขอนแก่น' },
  { pid: '22', v: 'จันทบุรี' },
  { pid: '24', v: 'ฉะเชิงเทรา' },
  { pid: '20', v: 'ชลบุรี' },
  { pid: '18', v: 'ชัยนาท' },
  { pid: '36', v: 'ชัยภูมิ' },
  { pid: '86', v: 'ชุมพร' },
  { pid: '57', v: 'เชียงราย' },
  { pid: '50', v: 'เชียงใหม่' },
  { pid: '92', v: 'ตรัง' },
  { pid: '23', v: 'ตราด' },
  { pid: '63', v: 'ตาก' },
  { pid: '26', v: 'นครนายก' },
  { pid: '73', v: 'นครปฐม' },
  { pid: '48', v: 'นครพนม' },
  { pid: '30', v: 'นครราชสีมา' },
  { pid: '80', v: 'นครศรีธรรมราช' },
  { pid: '60', v: 'นครสวรรค์' },
  { pid: '12', v: 'นนทบุรี' },
  { pid: '96', v: 'นราธิวาส' },
  { pid: '55', v: 'น่าน' },
  { pid: '38', v: 'บึงกาฬ' },
  { pid: '31', v: 'บุรีรัมย์' },
  { pid: '13', v: 'ปทุมธานี' },
  { pid: '77', v: 'ประจวบคีรีขันธ์' },
  { pid: '25', v: 'ปราจีนบุรี' },
  { pid: '94', v: 'ปัตตานี' },
  { pid: '14', v: 'พระนครศรีอยุธยา' },
  { pid: '56', v: 'พะเยา' },
  { pid: '82', v: 'พังงา' },
  { pid: '93', v: 'พัทลุง' },
  { pid: '66', v: 'พิจิตร' },
  { pid: '65', v: 'พิษณุโลก' },
  { pid: '76', v: 'เพชรบุรี' },
  { pid: '67', v: 'เพชรบูรณ์' },
  { pid: '54', v: 'แพร่' },
  { pid: '83', v: 'ภูเก็ต' },
  { pid: '44', v: 'มหาสารคาม' },
  { pid: '49', v: 'มุกดาหาร' },
  { pid: '58', v: 'แม่ฮ่องสอน' },
  { pid: '35', v: 'ยโสธร' },
  { pid: '95', v: 'ยะลา' },
  { pid: '45', v: 'ร้อยเอ็ด' },
  { pid: '85', v: 'ระนอง' },
  { pid: '21', v: 'ระยอง' },
  { pid: '70', v: 'ราชบุรี' },
  { pid: '16', v: 'ลพบุรี' },
  { pid: '52', v: 'ลำปาง' },
  { pid: '51', v: 'ลำพูน' },
  { pid: '42', v: 'เลย' },
  { pid: '33', v: 'ศรีสะเกษ' },
  { pid: '47', v: 'สกลนคร' },
  { pid: '90', v: 'สงขลา' },
  { pid: '91', v: 'สตูล' },
  { pid: '11', v: 'สมุทรปราการ' },
  { pid: '75', v: 'สมุทรสงคราม' },
  { pid: '74', v: 'สมุทรสาคร' },
  { pid: '27', v: 'สระแก้ว' },
  { pid: '19', v: 'สระบุรี' },
  { pid: '17', v: 'สิงห์บุรี' },
  { pid: '64', v: 'สุโขทัย' },
  { pid: '72', v: 'สุพรรณบุรี' },
  { pid: '84', v: 'สุราษฎร์ธานี' },
  { pid: '32', v: 'สุรินทร์' },
  { pid: '43', v: 'หนองคาย' },
  { pid: '39', v: 'หนองบัวลำภู' },
  { pid: '15', v: 'อ่างทอง' },
  { pid: '37', v: 'อำนาจเจริญ' },
  { pid: '41', v: 'อุดรธานี' },
  { pid: '53', v: 'อุตรดิตถ์' },
  { pid: '61', v: 'อุทัยธานี' },
  { pid: '34', v: 'อุบลราชธานี' },
]

export const province_en = [
  { pid: '37', v: 'Amnat Charoen' },
  { pid: '15', v: 'Ang Thong' },
  { pid: '10', v: 'Bangkok' },
  { pid: '38', v: 'Bueng Kan' },
  { pid: '31', v: 'Buri Ram' },
  { pid: '24', v: 'Chachoengsao' },
  { pid: '18', v: 'Chai Nat' },
  { pid: '36', v: 'Chaiyaphum' },
  { pid: '22', v: 'Chanthaburi' },
  { pid: '50', v: 'Chiang Mai' },
  { pid: '57', v: 'Chiang Rai' },
  { pid: '20', v: 'Chon Buri' },
  { pid: '86', v: 'Chumphon' },
  { pid: '46', v: 'Kalasin' },
  { pid: '62', v: 'Kamphaeng Phet' },
  { pid: '71', v: 'Kanchanaburi' },
  { pid: '40', v: 'Khon Kaen' },
  { pid: '81', v: 'Krabi' },
  { pid: '52', v: 'Lampang' },
  { pid: '51', v: 'Lamphun' },
  { pid: '42', v: 'Loei' },
  { pid: '16', v: 'Lop Buri' },
  { pid: '58', v: 'Mae Hong Son' },
  { pid: '44', v: 'Maha Sarakham' },
  { pid: '49', v: 'Mukdahan' },
  { pid: '26', v: 'Nakhon Nayok' },
  { pid: '73', v: 'Nakhon Pathom' },
  { pid: '48', v: 'Nakhon Phanom' },
  { pid: '30', v: 'Nakhon Ratchasima' },
  { pid: '60', v: 'Nakhon Sawan' },
  { pid: '80', v: 'Nakhon Si Thammarat' },
  { pid: '55', v: 'Nan' },
  { pid: '96', v: 'Narathiwat' },
  { pid: '39', v: 'Nong Bua Lam Phu' },
  { pid: '43', v: 'Nong Khai' },
  { pid: '12', v: 'Nonthaburi' },
  { pid: '13', v: 'Pathum Thani' },
  { pid: '94', v: 'Pattani' },
  { pid: '82', v: 'Phang-nga' },
  { pid: '93', v: 'Phatthalung' },
  { pid: '56', v: 'Phayao' },
  { pid: '67', v: 'Phetchabun' },
  { pid: '76', v: 'Phetchaburi' },
  { pid: '66', v: 'Phichit' },
  { pid: '65', v: 'Phitsanulok' },
  { pid: '14', v: 'Phra Nakhon Si Ayutthaya' },
  { pid: '54', v: 'Phrae' },
  { pid: '83', v: 'Phuket' },
  { pid: '25', v: 'Prachin Buri' },
  { pid: '77', v: 'Prachuap Khiri Khan' },
  { pid: '85', v: 'Ranong' },
  { pid: '70', v: 'Ratchaburi' },
  { pid: '21', v: 'Rayong' },
  { pid: '45', v: 'Roi Et' },
  { pid: '27', v: 'Sa kaeo' },
  { pid: '47', v: 'Sakon Nakhon' },
  { pid: '11', v: 'Samut Prakarn' },
  { pid: '74', v: 'Samut Sakhon' },
  { pid: '75', v: 'Samut Songkhram' },
  { pid: '19', v: 'Saraburi' },
  { pid: '91', v: 'Satun' },
  { pid: '33', v: 'Si Sa Ket' },
  { pid: '17', v: 'Sing Buri' },
  { pid: '90', v: 'Songkhla' },
  { pid: '64', v: 'Sukhothai' },
  { pid: '72', v: 'Suphan Buri' },
  { pid: '84', v: 'Surat Thani' },
  { pid: '32', v: 'Surin' },
  { pid: '63', v: 'Tak' },
  { pid: '92', v: 'Trang' },
  { pid: '23', v: 'Trat' },
  { pid: '34', v: 'Ubon Ratchathani' },
  { pid: '41', v: 'Udon Thani' },
  { pid: '61', v: 'Uthai Thani' },
  { pid: '53', v: 'Uttaradit' },
  { pid: '95', v: 'Yala' },
  { pid: '35', v: 'Yasothon' },
]
